library_source: C:/Users/things/
export_path: C:/Users/desktop/

site_name: Myllaume
author: Guillaume Brioudes
description: >
  Je m'appelle Guillaume Brioudes, suis développeur web et étudiant en documentation numérique.
  Je me sers de ce blog comme d'un carnet pour mes recherche en développement et architecture documentaire.